//            0 1 2 3 4 5 6 7 8 9 10             
// const array = [3,2,3,5,1,5,2,3,5,3,6,21,543,423,4,234,23,42,34,32,4,324,32,4,23,423,4,23,423,4,234,23,412,4];

//for(u = 1 ; u <= 10 ; u++){
//    console.log(u);
//}

let num = 1;
let num1 = 1.4;
let string = '1';
let boleano = true;

let objeto = {
    nome: 'fabricio',
    idade: 24,
    cpf: 12312312312
}

let array = [2,31,3,124,12,32,412,4];


// console.log(typeof num,num);
// console.log(typeof num1,num1);
// console.log(typeof string,string);
// console.log(typeof boleano,boleano);
// console.log(typeof objeto,objeto);
// console.log(typeof array,array);

console.log(objeto)